# Generated by Django 5.2.9 on 2026-02-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_achievement_workout_customerprofile_workoutexercise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="weekly_schedule",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
