# Generated by Django 5.2.9 on 2026-02-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_customerprofile_weekly_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerprofile",
            name="priority_muscles",
        ),
    ]
