# Generated by Django 5.2.9 on 2026-02-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_customerprofile_priority_muscles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="training_days",
            field=models.IntegerField(
                choices=[
                    (1, "1 Day"),
                    (2, "2 Days"),
                    (3, "3 Days"),
                    (4, "4 Days"),
                    (5, "5 Days"),
                    (6, "6 Days"),
                ]
            ),
        ),
    ]
