# Generated by Django 5.2.9 on 2026-02-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_customerprofile_training_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=45),
        ),
    ]
