# Generated by Django 5.2.9 on 2026-02-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_workout_duration_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
            ),
        ),
    ]
