# Generated by Django 5.2.9 on 2026-02-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_customerprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="category",
            field=models.CharField(
                choices=[
                    ("consistency", "Consistency / Attendance"),
                    ("muscle", "Muscle-Specific"),
                    ("savage", "Savage / Failure"),
                    ("discipline", "Discipline / Mindset"),
                    ("fun", "Fun / Flex"),
                ],
                default="fun",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
