# Generated by Django 5.2.9 on 2026-02-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_achievement_category_achievement_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="savage_mode",
            field=models.BooleanField(default=False),
        ),
    ]
