# Generated by Django 5.2.9 on 2026-02-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_customerprofile_savage_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutexercise",
            name="is_warmup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="rest_time_seconds",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
