# Generated by Django 5.2.9 on 2026-02-01 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_workoutexercise_is_warmup_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_logs",
                        to="core.member",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.workout",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
            },
        ),
    ]
