# Generated by Django 5.2.9 on 2026-02-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_workoutlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="font_size",
            field=models.CharField(
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="theme",
            field=models.CharField(
                choices=[("dark", "Dark Mode"), ("light", "Light Mode")],
                default="dark",
                max_length=10,
            ),
        ),
    ]
